import { dress } from "../assets/images"
export const products = [
    {
        id: 1,
        image : dress,
        name : "Vark Embroidered Light Beige Kurta with Palazzos & Dupatta",
        tags: ["Kurta", "Palazzos", "Dupatta"],
        price: 1999,
        color : "Light Beige",
        size : ["S", "M", "L", "XL", "XXL"],
        quantity : 1,
        description : "Light beige embroidered kurta with palazzos & dupatta",	
        isFavorite: false, 
    },
    {
        id: 2,
        image : dress,
        name : "Vark Embroidered Light Beige Kurta with Palazzos & Dupatta",
        tags: ["Kurta", "Palazzos", "Dupatta"],
        price: 1999,
        color : "Light Beige",
        size : ["S", "M", "L", "XL", "XXL"],
        quantity : 1,
        description : "Light beige embroidered kurta with palazzos & dupatta",	
        isFavorite: false, 
    },
    {
        id: 3,
        image : dress,
        name : "Vark Embroidered Light Beige Kurta with Palazzos & Dupatta",
        tags: ["Kurta", "Palazzos", "Dupatta"],
        price: 1999,
        color : "Light Beige",
        size : ["S", "M", "L", "XL", "XXL"],
        quantity : 1,
        description : "Light beige embroidered kurta with palazzos & dupatta",	
        isFavorite: false, 
    },
    {
        id: 4,
        image : dress,
        name : "Vark Embroidered Light Beige Kurta with Palazzos & Dupatta",
        tags: ["Kurta", "Palazzos", "Dupatta"],
        price: 1999,
        color : "Light Beige",
        size : ["S", "M", "L", "XL", "XXL"],
        quantity : 1,
        description : "Light beige embroidered kurta with palazzos & dupatta",	
        isFavorite: false, 
    },
    {
        id: 5,
        image : dress,
        name : "Vark Embroidered Light Beige Kurta with Palazzos & Dupatta",
        tags: ["Kurta", "Palazzos", "Dupatta"],
        price: 1999,
        color : "Light Beige",
        size : ["S", "M", "L", "XL", "XXL"],
        quantity : 1,
        description : "Light beige embroidered kurta with palazzos & dupatta",	
        isFavorite: false, 
    },
    {
        id: 6,
        image : dress,
        name : "Vark Embroidered Light Beige Kurta with Palazzos & Dupatta",
        tags: ["Kurta", "Palazzos", "Dupatta"],
        price: 1999,
        color : "Light Beige",
        size : ["S", "M", "L", "XL", "XXL"],
        quantity : 1,
        description : "Light beige embroidered kurta with palazzos & dupatta",
        isFavorite: false,
    },
    {
        id: 7,
        image : dress,
        name : "Vark Embroidered Light Beige Kurta with Palazzos & Dupatta",
        tags: ["Kurta", "Palazzos", "Dupatta"],
        price: 1999,
        color : "Light Beige",
        size : ["S", "M", "L", "XL", "XXL"],
        quantity : 1,
        description : "Light beige embroidered kurta with palazzos & dupatta",
        isFavorite: false,
    },
    {
        id: 8,
        image : dress,
        name : "Vark Embroidered Light Beige Kurta with Palazzos & Dupatta",
        tags: ["Kurta", "Palazzos", "Dupatta"],
        price: 1999,
        color : "Light Beige",
        size : ["S", "M", "L", "XL", "XXL"],
        quantity : 1,
        description : "Light beige embroidered kurta with palazzos & dupatta",
        isFavorite: false,
    },
    {
        id: 9,
        image : dress,
        name : "Vark Embroidered Light Beige Kurta with Palazzos & Dupatta",
        tags: ["Kurta", "Palazzos", "Dupatta"],
        price: 1999,
        color : "Light Beige",
        size : ["S", "M", "L", "XL", "XXL"],	
        quantity : 1,
        description : "Light beige embroidered kurta with palazzos & dupatta",
        isFavorite: false,
    },
    {
        id: 10,
        image : dress,
        name : "Vark Embroidered Light Beige Kurta with Palazzos & Dupatta",	
        tags: ["Kurta", "Palazzos", "Dupatta"],	
        price: 1999,	
        color : "Light Beige",	
        size : ["S", "M", "L", "XL", "XXL"],	
        quantity : 1,	
        description : "Light beige embroidered kurta with palazzos & dupatta",	
        isFavorite: false,	
    },
    {
        id: 11,
        image : dress,
        name : "Vark Embroidered Light Beige Kurta with Palazzos & Dupatta",	
        tags: ["Kurta", "Palazzos", "Dupatta"],	
        price: 1999,	
        color : "Light Beige",	
        size : ["S", "M", "L", "XL", "XXL"],	
        quantity : 1,	
        description : "Light beige embroidered kurta with palazzos & dupatta",	
        isFavorite: false,	
    },
    {
        id: 12,
        image : dress,
        name : "Vark Embroidered Light Beige Kurta with Palazzos & Dupatta",	
        tags: ["Kurta", "Palazzos", "Dupatta"],	
        price: 1999,	
        color : "Light Beige",	
        size : ["S", "M", "L", "XL", "XXL"],	
        quantity : 1,	
        description : "Light beige embroidered kurta with palazzos & dupatta",	
        isFavorite: false,	
    },
    {
        id: 13,
        image : dress,
        name : "Vark Embroidered Light Beige Kurta with Palazzos & Dupatta",	
        tags: ["Kurta", "Palazzos", "Dupatta"],	
        price: 1999,	
        color : "Light Beige",	
        size : ["S", "M", "L", "XL", "XXL"],	
        quantity : 1,	
        description : "Light beige embroidered kurta with palazzos & dupatta",	
        isFavorite: false,	
    },
]