import {
    GEGreen1, GEGreen2, GEGreen3, GEGreen4, GEGreen5, Wine1, Wine2, Wine3, Wine4, Wine5, Maroon1, Maroon2, Maroon3, Maroon4, Maroon5, Darknavy1, Darknavy2, Darknavy3, Darknavy4, Darknavy5, White1, White2, White3, White4, White5, Skyblue1, Skyblue2, Skyblue3, Skyblue4, Skyblue5
} from "../assets/images/men";

export const products = [
    {
        id: 1,
        images: [Maroon1, Maroon2, Maroon3, Maroon4, Maroon5],
        name: "Oxford Casual Shirts - Maroon",
        tags: ["Mens Wovens", "Casualwear", "Full Sleeves"],
        price: 1999,
        color: "Maroon",
        size: ["S", "M", "L", "XL", "XXL"],
        quantity: 1,
        description: "Machine Wash. Tumble Dry. Do Not Bleach. Wash Dark Color Separately. Warm Iron. Dry In Shade Do Not Iron On Print",
        isFavorite: false,
    },
    {
        id: 2,
        images: [Wine1, Wine2, Wine3, Wine4, Wine5],
        name: "Oxford Casual Shirts - Wine",
        tags: ["Mens Wovens", "Casualwear", "Full Sleeves"],
        price: 1999,
        color: "Sage Green",
        size: ["S", "M", "L", "XL", "XXL"],
        quantity: 1,
        description: "Machine Wash. Tumble Dry. Do Not Bleach. Wash Dark Color Separately. Warm Iron. Dry In Shade Do Not Iron On Print",
        isFavorite: false,
    },

    {
        id: 3,
        images: [Darknavy1, Darknavy2, Darknavy3, Darknavy4, Darknavy5],
        name: "Oxford Casual Shirts - Dark Navy",
        tags: ["Mens Wovens", "Casualwear", "Full Sleeves"],
        price: 1999,
        color: "Dark Navy",
        size: ["S", "M", "L", "XL", "XXL"],
        quantity: 1,
        description: "Machine Wash. Tumble Dry. Do Not Bleach. Wash Dark Color Separately. Warm Iron. Dry In Shade Do Not Iron On Print",
        isFavorite: false,
    },
    {
        id: 4,
        images: [Skyblue1, Skyblue2, Skyblue3, Skyblue4, Skyblue5],
        name: "Oxford Casual Shirts - Sky Blue",
        tags: ["Mens Wovens", "Casualwear", "Full Sleeves"],
        price: 1999,
        color: "Sky Blue",
        size: ["S", "M", "L", "XL", "XXL"],
        quantity: 1,
        description: "Machine Wash. Tumble Dry. Do Not Bleach. Wash Dark Color Separately. Warm Iron. Dry In Shade Do Not Iron On Print",
        isFavorite: false,
    },
    {
        id: 5,
        images: [GEGreen1, GEGreen2, GEGreen3, GEGreen4, GEGreen5],
        name: "Oxford Casual Shirts - Sage Green",
        tags: ["Mens Wovens", "Casualwear", "Full Sleeves"],
        price: 1999,
        color: "Sage Green",
        size: ["S", "M", "L", "XL", "XXL"],
        quantity: 1,
        description: "Machine Wash. Tumble Dry. Do Not Bleach. Wash Dark Color Separately. Warm Iron. Dry In Shade Do Not Iron On Print",
        isFavorite: false,
    },
    {
        id: 6,
        images: [White1, White2, White3, White4, White5],
        name: "Oxford Casual Shirts - White",
        tags: ["Mens Wovens", "Casualwear", "Full Sleeves"],
        price: 1999,
        color: "White",
        size: ["S", "M", "L", "XL", "XXL"],
        quantity: 1,
        description: "Machine Wash. Tumble Dry. Do Not Bleach. Wash Dark Color Separately. Warm Iron. Dry In Shade Do Not Iron On Print",
        isFavorite: false,
    },
    {
        id: 7,
        images: [GEGreen1, GEGreen2, GEGreen3, GEGreen4, GEGreen5],
        name: "Oxford Casual Shirts - Sage Green",
        tags: ["Mens Wovens", "Casualwear", "Full Sleeves"],
        price: 1999,
        color: "Sage Green",
        size: ["S", "M", "L", "XL", "XXL"],
        quantity: 1,
        description: "Machine Wash. Tumble Dry. Do Not Bleach. Wash Dark Color Separately. Warm Iron. Dry In Shade Do Not Iron On Print",
        isFavorite: false,
    },
    {
        id: 8,
        images: [White1, White2, White3, White4, White5],
        name: "Oxford Casual Shirts - White",
        tags: ["Mens Wovens", "Casualwear", "Full Sleeves"],
        price: 1999,
        color: "White",
        size: ["S", "M", "L", "XL", "XXL"],
        quantity: 1,
        description: "Machine Wash. Tumble Dry. Do Not Bleach. Wash Dark Color Separately. Warm Iron. Dry In Shade Do Not Iron On Print",
        isFavorite: false,
    },
    {
        id: 9,
        images: [Darknavy1, Darknavy2, Darknavy3, Darknavy4, Darknavy5],
        name: "Oxford Casual Shirts - Dark Navy",
        tags: ["Mens Wovens", "Casualwear", "Full Sleeves"],
        price: 1999,
        color: "Dark Navy",
        size: ["S", "M", "L", "XL", "XXL"],
        quantity: 1,
        description: "Machine Wash. Tumble Dry. Do Not Bleach. Wash Dark Color Separately. Warm Iron. Dry In Shade Do Not Iron On Print",
        isFavorite: false,
    },
    {
        id: 10,
        images: [Skyblue1, Skyblue2, Skyblue3, Skyblue4, Skyblue5],
        name: "Oxford Casual Shirts - Sky Blue",
        tags: ["Mens Wovens", "Casualwear", "Full Sleeves"],
        price: 1999,
        color: "Sky Blue",
        size: ["S", "M", "L", "XL", "XXL"],
        quantity: 1,
        description: "Machine Wash. Tumble Dry. Do Not Bleach. Wash Dark Color Separately. Warm Iron. Dry In Shade Do Not Iron On Print",
        isFavorite: false,
    },
    {
        id: 11,
        images: [Maroon1, Maroon2, Maroon3, Maroon4, Maroon5],
        name: "Oxford Casual Shirts - Maroon",
        tags: ["Mens Wovens", "Casualwear", "Full Sleeves"],
        price: 1999,
        color: "Maroon",
        size: ["S", "M", "L", "XL", "XXL"],
        quantity: 1,
        description: "Machine Wash. Tumble Dry. Do Not Bleach. Wash Dark Color Separately. Warm Iron. Dry In Shade Do Not Iron On Print",
        isFavorite: false,
    },
    {
        id: 12,
        images: [Wine1, Wine2, Wine3, Wine4, Wine5],
        name: "Oxford Casual Shirts - Wine",
        tags: ["Mens Wovens", "Casualwear", "Full Sleeves"],
        price: 1999,
        color: "Sage Green",
        size: ["S", "M", "L", "XL", "XXL"],
        quantity: 1,
        description: "Machine Wash. Tumble Dry. Do Not Bleach. Wash Dark Color Separately. Warm Iron. Dry In Shade Do Not Iron On Print",
        isFavorite: false,
    }
]