import { GEGreen1,White,Wine, Maroon, Darknavy, Skyblue } from "../assets/images/men";

export const products = [
    {
        id: 1,
        image : GEGreen1,
        name : "Oxford Casual Shirts - Sage Green",
        tags: ["Mens Wovens", "Casualwear", "Full Sleeves"],
        price: 1999,
        color : "Sage Green",
        size : ["S", "M", "L", "XL", "XXL"],
        quantity : 1,
        description : "Machine Wash. Tumble Dry. Do Not Bleach. Wash Dark Color Separately. Warm Iron. Dry In Shade Do Not Iron On Print",	
        isFavorite: false, 
    },
    {
        id: 2,
        image : White,
        name : "Oxford Casual Shirts - White",
        tags: ["Mens Wovens", "Casualwear", "Full Sleeves"],
        price: 1999,
        color : "White",
        size : ["S", "M", "L", "XL", "XXL"],
        quantity : 1,
        description : "Machine Wash. Tumble Dry. Do Not Bleach. Wash Dark Color Separately. Warm Iron. Dry In Shade Do Not Iron On Print",	
        isFavorite: false, 
    },
    {
        id: 3,
        image : Darknavy,
        name : "Oxford Casual Shirts - Dark Navy",
        tags: ["Mens Wovens", "Casualwear", "Full Sleeves"],
        price: 1999,
        color : "Dark Navy",
        size : ["S", "M", "L", "XL", "XXL"],
        quantity : 1,
        description : "Machine Wash. Tumble Dry. Do Not Bleach. Wash Dark Color Separately. Warm Iron. Dry In Shade Do Not Iron On Print",	
        isFavorite: false, 
    },
    {
        id: 4,
        image : Skyblue,
        name : "Oxford Casual Shirts - Sky Blue",
        tags: ["Mens Wovens", "Casualwear", "Full Sleeves"],
        price: 1999,
        color : "Sky Blue",
        size : ["S", "M", "L", "XL", "XXL"],
        quantity : 1,
        description : "Machine Wash. Tumble Dry. Do Not Bleach. Wash Dark Color Separately. Warm Iron. Dry In Shade Do Not Iron On Print",	
        isFavorite: false, 
    },
    {
        id: 5,
        image : Maroon,
        name : "Oxford Casual Shirts - Maroon",
        tags: ["Mens Wovens", "Casualwear", "Full Sleeves"],
        price: 1999,
        color : "Maroon",
        size : ["S", "M", "L", "XL", "XXL"],
        quantity : 1,
        description : "Machine Wash. Tumble Dry. Do Not Bleach. Wash Dark Color Separately. Warm Iron. Dry In Shade Do Not Iron On Print",	
        isFavorite: false, 
    },
    {
        id: 6,
        image : Wine,
        name : "Oxford Casual Shirts - Wine",
        tags: ["Mens Wovens", "Casualwear", "Full Sleeves"],
        price: 1999,
        color : "Sage Green",
        size : ["S", "M", "L", "XL", "XXL"],
        quantity : 1,
        description : "Machine Wash. Tumble Dry. Do Not Bleach. Wash Dark Color Separately. Warm Iron. Dry In Shade Do Not Iron On Print",	
        isFavorite: false, 
    },
    {
        id: 7,
        image : GEGreen1,
        name : "Oxford Casual Shirts - Sage Green",
        tags: ["Mens Wovens", "Casualwear", "Full Sleeves"],
        price: 1999,
        color : "Sage Green",
        size : ["S", "M", "L", "XL", "XXL"],
        quantity : 1,
        description : "Machine Wash. Tumble Dry. Do Not Bleach. Wash Dark Color Separately. Warm Iron. Dry In Shade Do Not Iron On Print",	
        isFavorite: false, 
    },
    {
        id: 8,
        image : White,
        name : "Oxford Casual Shirts - White",
        tags: ["Mens Wovens", "Casualwear", "Full Sleeves"],
        price: 1999,
        color : "White",
        size : ["S", "M", "L", "XL", "XXL"],
        quantity : 1,
        description : "Machine Wash. Tumble Dry. Do Not Bleach. Wash Dark Color Separately. Warm Iron. Dry In Shade Do Not Iron On Print",	
        isFavorite: false, 
    },
    {
        id: 9,
        image : Darknavy,
        name : "Oxford Casual Shirts - Dark Navy",
        tags: ["Mens Wovens", "Casualwear", "Full Sleeves"],
        price: 1999,
        color : "Dark Navy",
        size : ["S", "M", "L", "XL", "XXL"],
        quantity : 1,
        description : "Machine Wash. Tumble Dry. Do Not Bleach. Wash Dark Color Separately. Warm Iron. Dry In Shade Do Not Iron On Print",	
        isFavorite: false, 
    },
    {
        id: 10,
        image : Skyblue,
        name : "Oxford Casual Shirts - Sky Blue",
        tags: ["Mens Wovens", "Casualwear", "Full Sleeves"],
        price: 1999,
        color : "Sky Blue",
        size : ["S", "M", "L", "XL", "XXL"],
        quantity : 1,
        description : "Machine Wash. Tumble Dry. Do Not Bleach. Wash Dark Color Separately. Warm Iron. Dry In Shade Do Not Iron On Print",	
        isFavorite: false, 
    },
    {
        id: 11,
        image : Maroon,
        name : "Oxford Casual Shirts - Maroon",
        tags: ["Mens Wovens", "Casualwear", "Full Sleeves"],
        price: 1999,
        color : "Maroon",
        size : ["S", "M", "L", "XL", "XXL"],
        quantity : 1,
        description : "Machine Wash. Tumble Dry. Do Not Bleach. Wash Dark Color Separately. Warm Iron. Dry In Shade Do Not Iron On Print",	
        isFavorite: false, 
    },
    {
        id: 12,
        image : Wine,
        name : "Oxford Casual Shirts - Wine",
        tags: ["Mens Wovens", "Casualwear", "Full Sleeves"],
        price: 1999,
        color : "Sage Green",
        size : ["S", "M", "L", "XL", "XXL"],
        quantity : 1,
        description : "Machine Wash. Tumble Dry. Do Not Bleach. Wash Dark Color Separately. Warm Iron. Dry In Shade Do Not Iron On Print",	
        isFavorite: false, 
    },
]